### PR TITLE
note that webpack 2 supports `import()`

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by graingert** [comment]
probably worth deprecating this module now.

**Comment by ljharb** [comment]
@graingert absolutely not, it's still crucial for webpack 1 usage.

**Comment by graingert** [comment]
@ljharb but webpack 1 is old and broken now.

**Comment by ysangkok** [comment]
Is it not irrelevant whether one considers this repo obsolete or not? This pull request is just about notifying users that they don't need to use this with Webpack 2. Nothing more, nothing less.

**Comment by chicoxyzzy** [comment]
why do you think it's broken? most of people still use it for their projects

**Comment by ljharb** [comment]
@graingert actually webpack 2 is potentially much more broken, because it reifies more strongly *incorrect* ES module semantics that *will definitely break* when module loading in node is resolved, which is why Airbnb will likely not use webpack 2, and why I strongly recommend everybody avoid using non-babel `import`/`export` semantics (since Babel's broken semantics are popular enough that there will be a migration story).

**Comment by xzyfer** [comment]
> it reifies more strongly incorrect ES module semantics

@ljharb can you please elaborate, or link to relevant discussion?

**Comment by ljharb** [comment]
@xzyfer I'm specifically referring to when you `import` a CJS module and use named imports (obviously when you `import` something that's written as an ES module in your own app, things are fine). Everyone's code that's doing `import { PropTypes } from 'react'` is going to break when node eventually ships modules.

**Comment by timdorr** [comment]
Since this was [linked on reddit](https://www.reddit.com/r/javascript/comments/5rikrz/why_airbnb_will_never_use_webpack_2/) and before everyone throws @ljharb under the bus, first [read this cogent comment explaining the situation](https://www.reddit.com/r/javascript/comments/5rikrz/why_airbnb_will_never_use_webpack_2/dd7qihm/). Jordan's just the messenger here. [The actual spec](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md) is where this is all going down and where you should raise your pitchforks 😄

**Comment by FagnerMartinsBrack** [comment]
<strike>Does anybody have the link of any relevant discussion from Webpack's team about this?</strike>

Nevermind, it's right [on Reddit](https://www.reddit.com/r/javascript/comments/5rikrz/why_airbnb_will_never_use_webpack_2/dd7s5e1/), they opened a discussion about this (although as from the date of this comment it only has 2 comments).

**Comment by graingert** [comment]
probably worth deprecating this module now, because webpack 1 is deprecated.

**Comment by graingert** [comment]
@ysangkok can you rebase this PR?

**Comment by ysangkok** [comment]
@graingert ok now?

**Review by ljharb — APPROVED** [review]

**Pull request merged**
