### PR TITLE
[README] Add dynamic argument example fixes #10

### LINKED ISSUE #10: Minimal sample code snippet using `import()` or link to spec
Hi there!
Cool stuff :)

I just have a small suggestion: A few short lines of sample code would be nice. You show how to use it, but not the code it's supposed to run on.

Or a link to the `import()` spec. I was puzzled for a moment, since in my head `import` is a keyword for static module imports and not a function :)

### PR DESCRIPTION
**Pull request by agirton**
When reviewing the docs, thought it would be helpful to add an example. The test fixtures, explained things perfectly, so added the dynamic argument example to the README.

Now after about to open it looks like you have an open issue for this. So this should fix #10.

Let me know if I need to rework the formatting or placement 😄

### CODE REVIEW

**Comment by ljharb** [comment]
While these are good examples of how it will be transpiled and how the spec proposal works, because (i'm relatively certain) webpack's `require.ensure` requires a static hardcoded string, `import()` won't work properly here unless it is also a static hardcoded string.

**Comment by agirton** [comment]
Good point, that is how webpack's lazy load/ bundle works. Let me update the example. 

Would you be interested in an update to how it transpiles the code? This would require a bit more logic into the code and would have to walk through the tree once it finds that the argument is an `Identifier` and not a `StringLiteral`.  

### Example:

In:
```javascript
const MODULE = 'test-module';

import(MODULE);
import(`test-${MODULE}`);
```

Out:
```javascript
const MODULE = 'test-module';
new Promise(resolve => {
  require.ensure([], require => {
    resolve(require('test-module'));
  });
});
new Promise(resolve => {
  require.ensure([], require => {
    resolve(require(`test-test-module`));
  });
});
```

**Comment by ljharb** [comment]
No, since the module name could come from an import, or from a function call, etc, there's *no reliable means* of transpiling a non-static module name to a static one, and there'd be no way for the developer to know at build time if the transform was able to transform it or not.

**Comment by agirton** [comment]
Good point. I updated the example to use nested imports instead. This specific examples uses the require.context module, and it does in fact work. 

If you would like I can also add a fixture for this as well. I considered adding a comment about require.context, but the README already directs the user to the webpack docs that goes over this.

**Pull request closed without merging**
